
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Background
STAR_COUNT = 180
STAR_TWINKLE_SPEED = 1.6
NEBULA_CLOUD_COUNT = 26
NEBULA_DRIFT_SPEED = 5.0

# Player
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_SHIELD_REGEN_INTERVAL_SECONDS = 10.0

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Shots
SHOT_RADIUS = 5

# Economy / stations
STATION_RADIUS = 40
STATION_INTERACT_DISTANCE = 120
UPGRADE_FIRE_RATE_BASE_COST = 100
UPGRADE_FIRE_RATE_STEP_COST = 50
UPGRADE_FIRE_RATE_COOLDOWN_STEP = 0.025
UPGRADE_FIRE_RATE_MIN_COOLDOWN = 0.12
UPGRADE_SHIELD_BASE_COST = 100
UPGRADE_SHIELD_STEP_COST = 80
UPGRADE_SHIELD_MAX_LEVEL = 6
UPGRADE_MULTISHOT_BASE_COST = 130
UPGRADE_MULTISHOT_STEP_COST = 110
UPGRADE_MULTISHOT_MAX_LEVEL = 4
UPGRADE_TARGETING_BEAM_BASE_COST = 120
UPGRADE_TARGETING_BEAM_STEP_COST = 90
UPGRADE_TARGETING_BEAM_MAX_LEVEL = 3
UPGRADE_TARGETING_COMPUTER_BASE_COST = 150
UPGRADE_TARGETING_COMPUTER_STEP_COST = 110
UPGRADE_TARGETING_COMPUTER_MAX_LEVEL = 3
UPGRADE_WARP_DRIVE_BASE_COST = 180
UPGRADE_WARP_DRIVE_STEP_COST = 140
UPGRADE_WARP_DRIVE_MAX_LEVEL = 4
UPGRADE_SCANNER_BASE_COST = 140
UPGRADE_SCANNER_STEP_COST = 120
UPGRADE_SCANNER_MAX_LEVEL = 4
UPGRADE_MISSILE_BASE_COST = 190
UPGRADE_MISSILE_STEP_COST = 150
UPGRADE_MISSILE_MAX_LEVEL = 4
UPGRADE_CLOAK_BASE_COST = 220
UPGRADE_CLOAK_STEP_COST = 180
UPGRADE_CLOAK_MAX_LEVEL = 4
UPGRADE_CARGO_HOLD_BASE_COST = 170
UPGRADE_CARGO_HOLD_STEP_COST = 140
UPGRADE_CARGO_HOLD_MAX_LEVEL = 4
UPGRADE_ACCOMMODATIONS_BASE_COST = 160
UPGRADE_ACCOMMODATIONS_STEP_COST = 135
UPGRADE_ACCOMMODATIONS_MAX_LEVEL = 4
UPGRADE_ENGINE_TUNING_BASE_COST = 200
UPGRADE_ENGINE_TUNING_STEP_COST = 170
UPGRADE_ENGINE_TUNING_MAX_LEVEL = 4

STATION_LEVEL_BASE_COST = 260
STATION_LEVEL_STEP_COST = 220
STATION_LEVEL_MAX = 5
STATION_LASER_BASE_COST = 180
STATION_LASER_STEP_COST = 160
STATION_LASER_MAX = 5
STATION_MISSILE_BASE_COST = 220
STATION_MISSILE_STEP_COST = 190
STATION_MISSILE_MAX = 5

# Enemies
ENEMY_SPAWN_RATE_SECONDS = 4.0
ENEMY_SPEED = 160
ENEMY_VIEW_RANGE = 450
ENEMY_SHOOT_COOLDOWN_SECONDS = 1.5
ENEMY_SHOT_SPEED = 280
ENEMY_ALERT_LOSE_MULTIPLIER = 1.25
ENEMY_BOMBER_VIEW_RANGE = 250
ENEMY_HARASSER_VIEW_RANGE = 420
ENEMY_TANK_VIEW_RANGE = 300
